# Generated by Django 2.1.2 on 2019-02-19 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helps', '0001_initial'),
        ('market', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=200, unique=True, verbose_name='访问ip')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=200, verbose_name='用户ip')),
                ('ViewTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Commodity', verbose_name='商品')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.User_Info', verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='HelpsViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=200, verbose_name='用户ip')),
                ('ViewTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('HelpsArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helps.Article', verbose_name='文章')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.User_Info', verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='IpVisitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=200, verbose_name='用户ip')),
                ('loginTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.User_Info', verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=200, unique=True, verbose_name='访问ip')),
                ('visit_count', models.IntegerField(default=1, verbose_name='总访问次数')),
                ('five_min_visit', models.IntegerField(default=1, verbose_name='5分钟内访问次数')),
                ('lock', models.BooleanField(default=False, verbose_name='是否封锁')),
                ('time', models.ManyToManyField(to='log.IpVisitTime', verbose_name='时间')),
            ],
        ),
    ]
