# Generated by Django 2.1.2 on 2019-03-20 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20190320_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tailwind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskContent', models.CharField(default='', max_length=100, verbose_name='任务内容')),
                ('beginTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('endTime', models.DateTimeField(verbose_name='截止时间')),
                ('serviceType', models.CharField(choices=[('代送', '代送'), ('代办', '代办')], default='代送', max_length=100, verbose_name='服务类型')),
                ('beginPlace', models.CharField(default='', max_length=100, verbose_name='开始地点')),
                ('endPlace', models.CharField(blank=True, default='', max_length=100, verbose_name='结束地点')),
                ('status', models.CharField(choices=[('u', '未支付'), ('p', '等待接单'), ('t', '已被接单'), ('c', '已完成')], default='u', max_length=100, verbose_name='状态')),
                ('money', models.FloatField(default=0.0, verbose_name='金额')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User_Info', verbose_name='委托人')),
            ],
            options={
                'verbose_name': '顺风帮',
                'verbose_name_plural': '顺风帮列表',
                'db_table': 'tailwind',
                'ordering': ['-beginTime'],
            },
        ),
        migrations.CreateModel(
            name='TailwindOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('u', '未完成'), ('c', '已完成')], default='u', max_length=100, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('mandatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User_Info', verbose_name='受委托人')),
                ('tailwind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailwind.Tailwind', verbose_name='关联顺风帮订单')),
            ],
            options={
                'verbose_name': '顺风帮订单',
                'verbose_name_plural': '顺风帮订单列表',
                'db_table': 'tailwindOrder',
                'ordering': ['-create_time'],
            },
        ),
    ]
